owner: TheAPIGuysDev
repo: asyncthing-status

sites:
  - name: ASyncThing API (ping)
    url: https://api.asyncthing.com/ping/
    expectedStatusCodes: [200]
  - name: ASyncThing API (readiness)
    url: https://api.asyncthing.com/healthz/
    expectedStatusCodes: [200]
  - name: ASyncThing App
    url: https://app.asyncthing.com/

status-website:
  cname: status.asyncthing.com
  name: ASyncThing Status
  introTitle: ASyncThing system status
  introMessage: Real-time status of ASyncThing services.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/TheAPIGuysDev/asyncthing-status

assignees:
  - brumiser1550
